### ISSUE TITLE
report error on example "Diffusion from source"

### ISSUE THREAD

**Issue by forxhunter** [rengesser/Reaction-diffusion-simulator#1]
```Matlab
Example 1: Load model, make 1d simulation and plot.

str =

  1×3 cell 数组

    {' b_grad - k_deg_grad * gradients '}    {' gradients^2/(Km_grad^2 + gradients^2) * b_…'}    {' b_JAK   - k_deg_output2 * output2 - k_deg_…'}

错误使用 sym>convertChar (第 1580 行)
Character vectors and strings in the first argument can only specify a variable or number. To evaluate character vectors and strings representing symbolic
expressions, use 'str2sym'.

出错 sym>tomupad (第 1296 行)
        S = convertChar(x);

出错 sym (第 234 行)
                S.s = tomupad(x);

出错 cell2sym (第 31 行)
Csym = cellfun(conv, C, 'UniformOutput', false);

出错 sym>tomupad (第 1308 行)
    xsym = cell2sym(x);

出错 sym (第 234 行)
                S.s = tomupad(x);

出错 arSym (第 27 行)
        s = sym(str);

出错 reLoadModel (第 108 行)
eqSymbolic  = arSym(eq);

出错 SetupPDE (第 6 行)
reLoadModel('Diffusion_from_source.def')
```

**Comment by forxhunter** [comment]
I really have no idea why this happens, can u help me out?

**Comment by rengesser** [comment]
Which Matlab version you use? I think it is a problem of the version checking in https://github.com/rengesser/Reaction-diffusion-simulator/blob/master/arSym.m#L24

Can you replace line 24 in arSym with:

`if verLessThan('matlab','9.4')`

and test if this solves your issue. I have currently no Matlab available to test it on my own.

**Comment by forxhunter** [comment]
> Which Matlab version you use? I think it is a problem of the version checking in https://github.com/rengesser/Reaction-diffusion-simulator/blob/master/arSym.m#L24
> 
> Can you replace line 24 in arSym with:
> 
> `if verLessThan('matlab','9.4')`
> 
> and test if this solves your issue. I have currently no Matlab available to test it on my own.

My version is Matlab 2021a update 2
I find people on the internet said it's a problem after 2018a? But I am not sure how to fix it.@rengesser

**Comment by forxhunter** [comment]
thx, Problem solved by your line 24 solution.
